import { StyleSheet } from "react-native";
import { colors } from "../../theme/warm-colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  content: {
    padding: 20,
    paddingBottom: 120,
  },
  blobTopRight: {
    position: "absolute",
    top: -70,
    right: -70,
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: colors.accentLight,
    opacity: 0.28,
  },
  blobBottomLeft: {
    position: "absolute",
    bottom: 140,
    left: -80,
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: colors.lavenderDim,
    opacity: 0.44,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 18,
  },
  headerText: { flex: 1 },
  title: {
    color: colors.textPrimary,
    letterSpacing: -0.6,
  },
  subtitle: {
    color: colors.textSecondary,
    marginTop: 6,
    lineHeight: 22,
  },
  headerBadge: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 16,
  },
  contextCard: {
    backgroundColor: colors.heroFill,
    borderColor: colors.heroBorder,
    borderRadius: 24,
    padding: 18,
    marginBottom: 14,
    shadowColor: colors.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  contextTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  contextTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  progressPill: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  progress: {
    color: colors.accentDeep,
    fontSize: 12,
    fontWeight: "800",
  },
  contextRow: {
    flexDirection: "row",
    gap: 10,
  },
  contextItem: {
    flex: 1,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  contextLabel: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  contextValue: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  sectionTitle: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  actionCard: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 12,
    shadowColor: colors.accentDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  recommendedCard: {
    backgroundColor: colors.accentDim,
    borderColor: colors.accentLight,
  },
  completedCard: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderSoft,
  },
  actionContent: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  icon: {
    marginRight: 14,
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: "center",
    alignItems: "center",
  },
  iconRecommended: {
    backgroundColor: colors.surface,
  },
  iconCompleted: {
    marginRight: 14,
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: colors.streakBg,
    borderWidth: 1,
    borderColor: colors.streakBorder,
    justifyContent: "center",
    alignItems: "center",
  },
  actionDetails: {
    flex: 1,
  },
  actionTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 4,
  },
  actionTitle: {
    color: colors.textPrimary,
    flex: 1,
  },
  textCompleted: {
    color: colors.textSecondary,
    flex: 1,
  },
  actionDescription: {
    color: colors.textSecondary,
    lineHeight: 21,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
    flexWrap: "wrap",
  },
  durationChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  duration: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  statusChip: {
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: colors.streakBg,
    borderWidth: 1,
    borderColor: colors.streakBorder,
  },
  statusText: {
    color: colors.streakText,
    fontSize: 11,
    fontWeight: "800",
  },
  recommendedChip: {
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.accentLight,
  },
  recommendedText: {
    color: colors.accentDeep,
    fontSize: 11,
    fontWeight: "800",
  },
});
