import { StyleSheet } from "react-native";
import { N } from "../../theme/warm-colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: N.bg,
  },
  content: {
    padding: 20,
    paddingBottom: 120,
  },
  blobTopRight: {
    position: "absolute",
    top: -60,
    right: -70,
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: N.accentLight,
    opacity: 0.25,
  },
  blobBottomLeft: {
    position: "absolute",
    bottom: 180,
    left: -80,
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: N.lavenderDim,
    opacity: 0.48,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 18,
  },
  headerText: { flex: 1 },
  title: {
    color: N.textPrimary,
    letterSpacing: -0.6,
  },
  subtitle: {
    color: N.textSecondary,
    marginTop: 6,
    lineHeight: 22,
  },
  headerBadge: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: N.surfaceAlt,
    borderWidth: 1,
    borderColor: N.border,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 16,
  },
  heroCard: {
    backgroundColor: N.heroFill,
    borderColor: N.heroBorder,
    borderRadius: 24,
    padding: 20,
    marginBottom: 14,
    shadowColor: N.accentDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  heroTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 18,
  },
  heroKicker: {
    color: N.accentDeep,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  levelValue: {
    color: N.textPrimary,
    fontSize: 44,
    fontWeight: "800",
    lineHeight: 50,
    marginTop: 4,
  },
  xpPill: {
    backgroundColor: N.surface,
    borderWidth: 1,
    borderColor: N.border,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  xpPillText: {
    color: N.accentDeep,
    fontSize: 13,
    fontWeight: "700",
  },
  statsCard: {
    backgroundColor: N.surface,
    borderColor: N.border,
    borderRadius: 22,
    marginBottom: 14,
    shadowColor: N.accentDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statValue: {
    fontSize: 28,
    fontWeight: "800",
    color: N.textPrimary,
  },
  statLabel: {
    color: N.textMuted,
    marginTop: 4,
    textAlign: "center",
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: N.borderSoft,
  },
  xpBar: {
    height: 9,
    backgroundColor: N.surface,
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 8,
  },
  xpFill: {
    height: '100%',
    backgroundColor: N.accent,
    borderRadius: 20,
  },
  xpText: {
    color: N.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  nextCard: {
    backgroundColor: N.surface,
    borderColor: N.border,
    borderRadius: 22,
    marginBottom: 26,
    shadowColor: N.accentDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  nextHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  progressTitle: {
    color: N.textPrimary,
  },
  nextSubtitle: {
    color: N.textMuted,
    marginTop: 2,
  },
  progressMeta: {
    color: N.accentDeep,
    fontWeight: "700",
  },
  progressBar: {
    height: 9,
    backgroundColor: N.surfaceAlt,
    borderRadius: 20,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: N.accent,
    borderRadius: 20,
  },
  nextAwardRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: N.borderSoft,
  },
  nextIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: N.accentDim,
    borderWidth: 1,
    borderColor: N.border,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  nextAwardText: {
    flex: 1,
  },
  nextAwardTitle: {
    color: N.textPrimary,
    fontWeight: "700",
  },
  nextAwardDescription: {
    color: N.textSecondary,
    marginTop: 2,
  },
  categorySection: {
    marginBottom: 26,
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  categoryLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  categoryTitle: {
    color: N.textPrimary,
  },
  categoryCount: {
    color: N.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  achievementCard: {
    backgroundColor: N.surface,
    borderColor: N.border,
    borderRadius: 20,
    marginBottom: 10,
    padding: 16,
    shadowColor: N.accentDeep,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  lockedCard: {
    backgroundColor: N.surfaceAlt,
    borderColor: N.borderSoft,
  },
  achievementContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  iconContainer: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: N.accentDim,
    borderWidth: 1,
    borderColor: N.border,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  lockedIconContainer: {
    backgroundColor: N.surface,
    borderColor: N.borderSoft,
  },
  achievementIcon: {
    fontSize: 24,
  },
  achievementDetails: {
    flex: 1,
  },
  achievementTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 4,
  },
  achievementTitle: {
    color: N.textPrimary,
    flex: 1,
  },
  lockedTitle: {
    color: N.textSecondary,
  },
  achievementDescription: {
    color: N.textSecondary,
    lineHeight: 22,
  },
  lockedDescription: {
    color: N.textMuted,
  },
  statusPill: {
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: N.streakBg,
    borderWidth: 1,
    borderColor: N.streakBorder,
  },
  statusPillLocked: {
    backgroundColor: N.surface,
    borderColor: N.borderSoft,
  },
  statusText: {
    color: N.streakText,
    fontSize: 10,
    fontWeight: "700",
  },
  statusTextLocked: {
    color: N.textMuted,
  },
});
