/**
 * Centralized color constants for the MindEase application
 * All colors should be imported from this file, not hardcoded
 */

// Base color palette
export const COLORS = {
  // Background colors
  BACKGROUND_DARK: '#0D1117',
  BACKGROUND_DARKER: '#080D18',
  BACKGROUND_DARKEST: '#0C1220',
  BACKGROUND_LIGHT: '#FDF8F3',
  BACKGROUND_SECONDARY: '#F5EDE4',
  BACKGROUND_CARD: '#FFFFFF',
  BACKGROUND_CARD_WARM: '#FFF9F5',

  // Text colors
  TEXT_PRIMARY: '#F9FAFB',
  TEXT_SECONDARY: '#D1D5DB',
  TEXT_TERTIARY: '#9CA3AF',
  TEXT_MUTED: '#6B7280',
  TEXT_LIGHT: '#CBD5E1',
  TEXT_DARK: '#4A403A',
  TEXT_DARK_SECONDARY: '#8C7F74',
  TEXT_DARK_MUTED: '#B5A99B',

  // Primary brand colors
  PRIMARY: '#6366F1',
  PRIMARY_DARK: '#4F46E5',
  PRIMARY_LIGHT: '#818CF8',

  // Accent colors
  ACCENT: '#8B5CF6',
  ACCENT_DARK: '#7C3AED',
  ACCENT_LIGHT: '#F3EFF5',
  ACCENT_DEEP: '#6366F1',
  ACCENT_DIM: '#E8E8F0',

  // Success colors
  SUCCESS: '#10B981',
  SUCCESS_LIGHT: '#34D399',
  SUCCESS_DARK: '#059669',

  // Warning colors
  WARNING: '#F59E0B',
  WARNING_LIGHT: '#FCD34D',
  WARNING_DARK: '#D97706',

  // Error colors
  ERROR: '#EF4444',
  ERROR_LIGHT: '#F87171',
  ERROR_DARK: '#DC2626',

  // Border and divider colors
  BORDER: '#E5E7EB',
  BORDER_DARK: '#1F2937',
  BORDER_DARKER: '#141E30',
  DIVIDER: '#F3F4F6',
  DIVIDER_DARK: '#1E293B',

  // Tab bar colors
  TAB_BAR: '#FFFFFF',
  TAB_BAR_DARK: '#0C1220',
  TAB_BAR_BORDER: '#E5E7EB',
  TAB_BAR_BORDER_DARK: '#141E30',
  TAB_BAR_ACTIVE: '#6366F1',
  TAB_BAR_INACTIVE: '#9CA3AF',
  TAB_BAR_INACTIVE_DARK: '#3D4F6E',

  // Calming palette
  SAGE: '#9DB5A0',
  SAGE_LIGHT: '#E8F0E8',
  SAGE_DIM: '#E8F0E8',
  SAGE_DARK: '#1A2520',

  PEACH: '#E8B89C',
  PEACH_LIGHT: '#FDF0E8',
  PEACH_DARK: '#2A2018',

  LAVENDER: '#B8A9C4',
  LAVENDER_LIGHT: '#F3EFF5',
  LAVENDER_DIM: '#F3EFF5',
  LAVENDER_DARK: '#252030',

  SKY: '#A8C4D4',
  SKY_LIGHT: '#E8F0F5',
  SKY_DARK: '#1A2528',

  // Blob colors for decorative elements
  BLOB_1: '#F0E6D8',
  BLOB_2: '#E8F0EC',
  BLOB_3: '#F5E8F0',
  BLOB_1_DARK: '#1A1520',
  BLOB_2_DARK: '#1A2020',
  BLOB_3_DARK: '#201A25',

  // Specific mood colors
  MOOD_CALM: '#9DB5A0',
  MOOD_TENSE: '#8B5CF6',
  MOOD_ANXIOUS: '#B8A9C4',
  MOOD_EXHAUSTED: '#A07850',
  MOOD_EXHAUSTED_DIM: '#FFF5EC',
  MOOD_EXHAUSTED_BORDER: '#C4A070',
  MOOD_OVERWHELMED: '#C45050',
  MOOD_OVERWHELMED_DIM: '#FFF0EE',
  MOOD_OVERWHELMED_BORDER: '#E07070',

  // Exercise category colors
  EXERCISE_BREATHE: '#6366F1',
  EXERCISE_GROUND: '#9DB5A0',
  EXERCISE_MOVE: '#10B981',
  EXERCISE_RELEASE: '#B8A9C4',
  EXERCISE_DUMP: '#F59E0B',

  // Achievement colors
  ACHIEVEMENT_STREAK: '#F59E0B',
  ACHIEVEMENT_MILESTONE: '#10B981',
  ACHIEVEMENT_EXPLORER: '#6366F1',
  ACHIEVEMENT_MASTER: '#EC4899',

  // Progress and status colors
  PROGRESS_TRACK: '#374151',
  PROGRESS_FILL: '#10B981',
  PROGRESS_TRACK_DARK: '#1E293B',
  PROGRESS_FILL_DARK: '#8B5CF6',

  // UI element colors
  SURFACE: '#FFFFFF',
  SURFACE_DARK: '#141E30',
  HERO_FROM: '#E8B89C',
  HERO_TO: '#D4A574',
  BORDER_LIGHT: '#E5E7EB',
  BORDER_DARK_LIGHT: '#1F2937',

  // Modal colors
  MODAL_OVERLAY: '#000000AA',
  MODAL_CONTENT: '#0C1220',
  MODAL_CONTENT_BORDER: '#141E30',

  // Toggle colors
  TOGGLE_BACKGROUND: '#1A2235',
  TOGGLE_BORDER: '#2A3550',
  TOGGLE_ACTIVE: '#2563EB',
  TOGGLE_KNOB: '#3D4F6E',
  TOGGLE_KNOB_ACTIVE: '#FFFFFF',

  // Input colors
  INPUT_BACKGROUND: '#161B22',
  INPUT_BORDER: '#21262D',

  // Special colors
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  TRANSPARENT: 'transparent',
  PURPLE:'#e1fcf78b',

  // Opacity variants
  ACCENT_ALPHA_20: 'rgba(106,90,205,0.2)',
  ACCENT_ALPHA_25: 'rgba(106,90,205,0.25)',
  ACCENT_ALPHA_30: 'rgba(106,90,205,0.3)',
  BLACK_ALPHA_08: 'rgba(0,0,0,0.08)',
};

// Color aliases for semantic meaning
export const SEMANTIC_COLORS = {
  // Status colors
  SUCCESS: COLORS.SUCCESS,
  WARNING: COLORS.WARNING,
  ERROR: COLORS.ERROR,
  INFO: COLORS.PRIMARY,

  // Text colors
  TEXT_PRIMARY: COLORS.TEXT_PRIMARY,
  TEXT_SECONDARY: COLORS.TEXT_SECONDARY,
  TEXT_MUTED: COLORS.TEXT_MUTED,
  TEXT_INVERSE: COLORS.TEXT_DARK,

  // Background colors
  BACKGROUND_PRIMARY: COLORS.BACKGROUND_DARK,
  BACKGROUND_SECONDARY: COLORS.BACKGROUND_DARKER,
  BACKGROUND_CARD: COLORS.BACKGROUND_CARD,
  BACKGROUND_MODAL: COLORS.MODAL_CONTENT,

  // Interactive colors
  INTERACTIVE_PRIMARY: COLORS.PRIMARY,
  INTERACTIVE_SECONDARY: COLORS.ACCENT,
  INTERACTIVE_DISABLED: COLORS.TEXT_MUTED,
};

// Theme-specific color exports
export const LIGHT_THEME = {
  ...COLORS,
  background: COLORS.BACKGROUND_LIGHT,
  backgroundSecondary: COLORS.BACKGROUND_SECONDARY,
  card: COLORS.BACKGROUND_CARD,
  cardWarm: COLORS.BACKGROUND_CARD_WARM,
  text: COLORS.TEXT_DARK,
  textSecondary: COLORS.TEXT_DARK_SECONDARY,
  textTertiary: COLORS.TEXT_TERTIARY,
  textMuted: COLORS.TEXT_DARK_MUTED,
};

export const DARK_THEME = {
  ...COLORS,
  background: COLORS.BACKGROUND_DARK,
  backgroundSecondary: COLORS.BACKGROUND_DARKER,
  card: COLORS.SURFACE_DARK,
  cardWarm: COLORS.BACKGROUND_DARKER,
  text: COLORS.TEXT_PRIMARY,
  textSecondary: COLORS.TEXT_SECONDARY,
  textTertiary: COLORS.TEXT_TERTIARY,
  textMuted: COLORS.TEXT_MUTED,
};

export default COLORS;
