import COLORS from "../../constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.PURPLE },
  hero: { padding: 20, paddingBottom: 0 },
  eyebrow: {
    fontSize: 10,
    color: COLORS.TEXT_TERTIARY,
    letterSpacing: 1.4,
    fontWeight: "600",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: COLORS.TEXT_DARK,
    lineHeight: 32,
    marginBottom: 3,
  },
  heroAccent: { fontSize: 26, fontWeight: "700" },
  heroSub: {
    fontSize: 12,
    color: COLORS.TEXT_DARK_SECONDARY,
    marginBottom: 18,
  },
  playerCard: {
    backgroundColor: COLORS.BACKGROUND_CARD,
    borderRadius: 22,
    borderWidth: 0.5,
    borderColor: COLORS.BORDER,
    padding: 20,
    marginBottom: 16,
    overflow: "hidden",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  blobTR: {
    position: "absolute",
    top: -50,
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    opacity: 0.7,
  },
  blobBL: {
    position: "absolute",
    bottom: -40,
    left: -30,
    width: 110,
    height: 110,
    borderRadius: 55,
    opacity: 0.8,
  },
  albumWrap: { width: 64, height: 64, flexShrink: 0 },
  albumPulse: {
    position: "absolute",
    top: -3,
    right: -3,
    bottom: -3,
    left: -3,
    borderRadius: 17,
    borderWidth: 1.5,
    opacity: 0.35,
  },
  albumArt: {
    width: 64,
    height: 64,
    borderRadius: 14,
    borderWidth: 0.5,
    alignItems: "center",
    justifyContent: "center",
  },

  playerTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 18,
    zIndex: 1,
  },
  playerInfo: { flex: 1, minWidth: 0 },
  playerTrack: { fontSize: 15, fontWeight: "600", color: COLORS.TEXT_DARK },
  playerArtist: {
    fontSize: 12,
    color: COLORS.TEXT_DARK_SECONDARY,
    marginTop: 2,
  },
  nowBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginTop: 6,
    alignSelf: "flex-start",
  },
  badgeDot: { width: 5, height: 5, borderRadius: 3 },
  badgeTxt: { fontSize: 10, fontWeight: "600", letterSpacing: 0.3 },
  iconBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 0.5,
    alignItems: "center",
    justifyContent: "center",
  },
  waveform: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    height: 32,
    marginBottom: 14,
    paddingHorizontal: 2,
  },
  wvTime: { marginLeft: "auto", fontSize: 11, color: COLORS.TEXT_TERTIARY },
  progressWrap: { zIndex: 1, marginBottom: 16 },
  progressTimes: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: -4,
  },
  progressTime: { fontSize: 10, color: COLORS.TEXT_TERTIARY },
  controls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    zIndex: 1,
  },
  ctrlGroup: { flexDirection: "row", alignItems: "center", gap: 10 },
  ctrlBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 0.5,
    borderColor: COLORS.BORDER,
    backgroundColor: COLORS.BACKGROUND_SECONDARY,
    alignItems: "center",
    justifyContent: "center",
  },
  playBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  volRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 0,
    paddingTop: 4,
    paddingBottom: 20,
  },
  sectionHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  secTitle: { fontSize: 14, fontWeight: "700", color: COLORS.TEXT_DARK },
  secLink: { fontSize: 11, fontWeight: "500" },
  moodGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  moodTile: {
    width: "47%",
    backgroundColor: COLORS.BACKGROUND_CARD,
    borderWidth: 0.5,
    borderColor: COLORS.BORDER,
    borderRadius: 16,
    padding: 14,
    gap: 6,
  },
  tileIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  tileLabel: { fontSize: 13, fontWeight: "700", color: COLORS.TEXT_DARK },
  tileCount: { fontSize: 11, color: COLORS.TEXT_DARK_SECONDARY },
  chipScroll: { flexGrow: 0, paddingVertical: 0, marginBottom: 4 },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: COLORS.BORDER,
    backgroundColor: COLORS.BACKGROUND_CARD,
  },
  chipText: {
    fontSize: 12,
    color: COLORS.TEXT_DARK_SECONDARY,
    fontWeight: "500",
  },
  chipTextOn: { color: COLORS.WHITE, fontWeight: "600" },
  trackList: { backgroundColor: COLORS.BACKGROUND_CARD, marginTop: 10 },
  groupLabel: {
    fontSize: 10,
    fontWeight: "600",
    color: COLORS.TEXT_TERTIARY,
    letterSpacing: 1,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 6,
  },
  trackRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderTopWidth: 0.5,
    borderTopColor: COLORS.BORDER,
  },
  trackArt: {
    width: 42,
    height: 42,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  trackInfo: { flex: 1, minWidth: 0 },
  trackName: { fontSize: 13, fontWeight: "500", color: COLORS.TEXT_DARK },
  trackMeta: { fontSize: 11, color: COLORS.TEXT_TERTIARY, marginTop: 2 },
  trackRight: { alignItems: "flex-end", gap: 4, flexShrink: 0 },
  trackDur: { fontSize: 11, color: COLORS.TEXT_TERTIARY },
  playIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 0.5,
    borderColor: COLORS.BORDER,
    backgroundColor: COLORS.BACKGROUND_LIGHT,
    alignItems: "center",
    justifyContent: "center",
  },
});
