import { StyleSheet } from "react-native";
import { colors } from "../../theme/warm-colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  content: { paddingBottom: 120 },
  blobTopRight: {
    position: "absolute",
    top: -70,
    right: -70,
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: colors.accentLight,
    opacity: 0.26,
  },
  blobBottomLeft: {
    position: "absolute",
    bottom: 180,
    left: -80,
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: colors.tealDim,
    opacity: 0.42,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    paddingTop: 24,
    paddingBottom: 14,
  },
  headerText: { flex: 1 },
  headerTitle: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: "800",
    color: colors.textPrimary,
    marginBottom: 6,
    letterSpacing: -0.6,
  },
  headerDesc: { fontSize: 14, color: colors.textSecondary, lineHeight: 21 },
  headerBadge: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 16,
  },

  section: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    marginHorizontal: 20,
    marginBottom: 20,
    overflow: "hidden",
    shadowColor: colors.accentDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  masterSection: {
    backgroundColor: colors.heroFill,
    borderColor: colors.heroBorder,
    borderRadius: 24,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.1,
    color: colors.textMuted,
    marginHorizontal: 20,
    marginBottom: 10,
    marginTop: 8,
    textTransform: "uppercase",
  },

  masterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 18,
    gap: 14,
  },
  masterCopy: { flex: 1 },
  masterLabel: { fontSize: 17, fontWeight: "800", color: colors.textPrimary },
  masterDesc: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
    marginTop: 4,
  },

  toggle: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  toggleActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  toggleKnob: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.textMuted,
  },
  toggleKnobActive: {
    backgroundColor: colors.surface,
    marginLeft: 20,
  },

  divider: { height: 1, backgroundColor: colors.borderSoft, marginHorizontal: 16 },
  bottomPad: { height: 40 },

  modalOverlay: {
    flex: 1,
    backgroundColor: "#1A3A1A66",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 20,
    width: 320,
    maxHeight: "80%",
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.textPrimary,
    marginBottom: 16,
    textAlign: "center",
  },

  pickerRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    height: 200,
  },
  pickerColumn: { flex: 1, alignItems: "center" },
  pickerLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
    marginBottom: 8,
  },
  pickerList: { maxHeight: 180 },
  pickerSeparator: { width: 32, alignItems: "center", justifyContent: "center" },
  pickerColon: { fontSize: 20, fontWeight: "800", color: colors.textPrimary },
  pickerItem: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  pickerItemActive: { backgroundColor: colors.accentDim },
  pickerItemText: { fontSize: 16, color: colors.textSecondary, fontWeight: "600" },
  pickerItemTextActive: { color: colors.accentDeep, fontWeight: "700" },

  confirmBtn: {
    backgroundColor: colors.accent,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 16,
  },
  confirmBtnText: { fontSize: 15, fontWeight: "700", color: colors.surface },

  dayItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginBottom: 4,
  },
  dayItemActive: { backgroundColor: colors.accentDim },
  dayItemText: { fontSize: 15, color: colors.textPrimary, fontWeight: "600" },
  dayItemTextActive: { color: colors.accentDeep, fontWeight: "700" },
});
