// styles.ts

import { N } from "../../theme/warm-colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // ── Layout ────────────────────────────────────────────────────────────────
  container: { flex: 1, backgroundColor: N.bg },
  scrollView: { flex: 1 },
  content: { paddingHorizontal: 20, paddingBottom: 140 },

  // ── Decorative blobs ──────────────────────────────────────────────────────
  blobTopRight: {
    position: "absolute",
    top: -50,
    right: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: N.accentLight,
    opacity: 0.25,
  },
  blobBottomLeft: {
    position: "absolute",
    bottom: 180,
    left: -70,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: N.tealDim,
    opacity: 0.4,
  },

  // ── Sticky header (outside ScrollView) ───────────────────────────────────
  stickyHeader: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 10,
    backgroundColor: N.bg,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerLeft: { flex: 1 },
  greetingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 2,
  },
  greetingText: {
    fontSize: 12,
    color: N.textMuted,
    fontWeight: "500",
    letterSpacing: 0.4,
  },
  appName: {
    fontSize: 27,
    fontWeight: "800",
    color: N.textPrimary,
    letterSpacing: -0.9,
    lineHeight: 32,
  },
  progressPill: {
    backgroundColor: N.surfaceAlt,
    borderRadius: 20,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: N.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  progressPillText: { fontSize: 11, color: N.accent, fontWeight: "600" },

  // ── Streak ────────────────────────────────────────────────────────────────
  streakBanner: {
    marginHorizontal: 20,
    marginBottom: 14,
    backgroundColor: N.streakBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: N.streakBorder,
    paddingHorizontal: 14,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  streakText: { fontSize: 13, color: N.streakText, fontWeight: "500", flex: 1 },

  // ── Intention strip ───────────────────────────────────────────────────────
  intentionWrap: { marginBottom: 18 },
  intentionLabel: {
    fontSize: 11,
    color: N.textMuted,
    fontWeight: "700",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  intentionRow: { flexDirection: "row", gap: 8 },
  intentionChip: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: N.border,
    backgroundColor: N.surface,
  },
  intentionChipActive: {
    borderColor: N.accent,
    backgroundColor: N.accentDim,
  },
  intentionChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: N.textSecondary,
  },
  intentionChipTextActive: { color: N.accentDeep },

  // ── Mood card ─────────────────────────────────────────────────────────────
  moodCard: {
    backgroundColor: N.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: N.border,
    paddingHorizontal: 18,
    paddingVertical: 18,
    marginBottom: 16,
    shadowColor: N.accentDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  moodQuestion: {
    fontSize: 14,
    color: N.textPrimary,
    fontWeight: "600",
    marginBottom: 14,
    letterSpacing: -0.1,
  },
  moodRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  moodPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
  },
  moodLabel: { fontSize: 12, fontWeight: "500" },

  // Intensity bar shown below mood pills
  intensityWrap: { marginTop: 14 },
  intensityTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: N.border,
    overflow: "hidden",
  },
  intensityFill: { height: "100%", borderRadius: 2 },
  intensityLabel: {
    fontSize: 11,
    color: N.textMuted,
    marginTop: 6,
    textAlign: "right",
    fontWeight: "400",
  },

  // ── Breathe zone (hero area) ──────────────────────────────────────────────
  breatheZone: { alignItems: "center", marginBottom: 20 },
  breatheRingOuter: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 1.5,
    borderColor: N.accentLight,
    alignItems: "center",
    justifyContent: "center",
  },
  breatheRingMiddle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: N.accentLight,
    alignItems: "center",
    justifyContent: "center",
  },
  breatheRingInner: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: N.heroFill,
    borderWidth: 1.5,
    borderColor: N.heroBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  breathePhaseText: {
    fontSize: 11,
    color: N.accentDeep,
    fontWeight: "600",
    letterSpacing: 0.5,
    marginTop: 12,
  },

  // ── Hero CTA card ─────────────────────────────────────────────────────────
  heroCard: {
    borderRadius: 24,
    marginBottom: 8,
    shadowColor: N.accentDeep,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 5,
  },
  heroInner: {
    backgroundColor: N.heroFill,
    borderRadius: 24,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderWidth: 1,
    borderColor: N.heroBorder,
    overflow: "hidden",
  },
  heroIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 17,
    backgroundColor: N.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: N.border,
    flexShrink: 0,
  },
  heroText: { flex: 1 },
  heroTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: N.textPrimary,
    letterSpacing: -0.4,
    marginBottom: 3,
  },
  heroSub: { fontSize: 12, color: N.textSecondary, lineHeight: 17 },
  heroChevron: { fontSize: 24, color: N.accentDeep, marginRight: -4 },
  heroHint: {
    textAlign: "center",
    fontSize: 11,
    color: N.textMuted,
    marginBottom: 24,
    letterSpacing: 0.2,
  },

  // ── Quick actions ─────────────────────────────────────────────────────────
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: N.textMuted,
    letterSpacing: 1.1,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  quickGrid: { flexDirection: "row", gap: 9, marginBottom: 28 },
  quickCard: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 18,
    borderRadius: 20,
    borderWidth: 1,
    gap: 6,
    shadowColor: "#00000008",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 1,
  },
  quickLabel: { fontSize: 11, fontWeight: "700", letterSpacing: 0.2 },
  quickUsed: { fontSize: 10, color: N.textMuted, marginTop: -2 },

  // ── Journey section ───────────────────────────────────────────────────────
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sectionAction: { fontSize: 12, color: N.accent, fontWeight: "600" },
  sessionScroll: { marginHorizontal: -20, paddingHorizontal: 20 },
  sessionCard: {
    backgroundColor: N.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: N.border,
    padding: 14,
    marginRight: 10,
    width: 220,
    shadowColor: N.accentDeep,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  sessionOrb: {
    width: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: N.accentDim,
    borderWidth: 1,
    borderColor: N.border,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  sessionWhat: {
    fontSize: 13,
    color: N.textPrimary,
    fontWeight: "600",
    marginBottom: 3,
  },
  sessionWhen: { fontSize: 11, color: N.textMuted },
  sessionBadge: {
    alignSelf: "flex-start",
    marginTop: 8,
    backgroundColor: N.streakBg,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: N.streakBorder,
  },
  sessionBadgeText: { fontSize: 10, color: N.streakText, fontWeight: "600" },

  // ── Insight wrapper ───────────────────────────────────────────────────────
  insightWrapper: { marginTop: 12, marginBottom: 4 },

  // ── Affirmation ───────────────────────────────────────────────────────────
  affirmationCard: {
    marginTop: 20,
    marginBottom: 8,
    backgroundColor: N.accentDim,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: N.accentLight,
    paddingHorizontal: 20,
    paddingVertical: 18,
    alignItems: "center",
  },
  affirmationText: {
    fontSize: 14,
    color: N.accentDeep,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 22,
    letterSpacing: 0.1,
  },
  affirmationSub: {
    fontSize: 11,
    color: N.textMuted,
    marginTop: 6,
    textAlign: "center",
  },

  // ── FAB container ─────────────────────────────────────────────────────────
  fabContainer: { position: "absolute", bottom: 0, left: 0, right: 0 },
});
