import { StyleSheet } from "react-native";
import { warmColors } from "../../theme/warm-colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: warmColors.bg },
  scrollView: { flex: 1 },
  content: { padding: 22, paddingBottom: 140 },
  blobTopRight: {
    position: "absolute",
    top: -60,
    right: -70,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: warmColors.surface,
  },
  blobBottomLeft: {
    position: "absolute",
    bottom: 200,
    left: -80,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: warmColors.overlay,
  },
  header: { marginBottom: 20 },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  headerLeft: { flex: 1 },
  greetingText: {
    fontSize: 12,
    color: warmColors.textMuted,
    fontWeight: "500",
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  appName: {
    fontSize: 28,
    fontWeight: "800",
    color: warmColors.textPrimary,
    letterSpacing: -1,
    lineHeight: 40,
  },
  progressPill: {
    backgroundColor: warmColors.surfaceDeep,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: warmColors.border,
  },
  progressPillText: { fontSize: 12, color: warmColors.sage, fontWeight: "600" },
  streakBanner: {
    backgroundColor: warmColors.streakBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: warmColors.streakBorder,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  streakText: { fontSize: 13, color: warmColors.streakText, fontWeight: "500" },
  moodCard: {
    backgroundColor: warmColors.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: warmColors.border,
    paddingHorizontal: 18,
    paddingVertical: 18,
    marginBottom: 18,
    shadowColor: warmColors.accentDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  moodQuestion: {
    fontSize: 15,
    color: warmColors.textPrimary,
    fontWeight: "600",
    marginBottom: 14,
    letterSpacing: -0.1,
  },
  moodRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  moodPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 22,
    borderWidth: 1,
  },
  moodLabel: { fontSize: 13, fontWeight: "500" },
  heroCard: {
    borderRadius: 24,
    marginBottom: 10,
    // Warm layered shadow
    shadowColor: warmColors.accentDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 6,
  },
  heroInner: {
    backgroundColor: warmColors.accentLight,
    borderRadius: 24,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: warmColors.heroFrom,
    overflow: "hidden",
  },
  heroIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: warmColors.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: warmColors.border,
    flexShrink: 0,
  },
  heroText: { flex: 1 },
  heroTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: warmColors.textPrimary,
    letterSpacing: -0.4,
    marginBottom: 3,
  },
  heroSub: {
    fontSize: 12,
    color: warmColors.textSecondary,
    fontWeight: "400",
    lineHeight: 17,
  },
  heroChevron: {
    fontSize: 26,
    color: warmColors.accentDeep,
    fontWeight: "300",
    marginRight: -4,
  },
  heroHint: {
    textAlign: "center",
    fontSize: 12,
    color: warmColors.textMuted,
    marginBottom: 26,
    fontWeight: "400",
    letterSpacing: 0.2,
  },
  quickGrid: { flexDirection: "row", gap: 10, marginBottom: 30 },
  quickCard: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 20,
    borderRadius: 20,
    borderWidth: 1,
    gap: 7,
    shadowColor: warmColors.textMuted,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 1,
  },
  quickLabel: { fontSize: 12, fontWeight: "700", letterSpacing: 0.2 },
  journeySection: { marginBottom: 4 },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 0,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: warmColors.textMuted,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 14,
  },
  sectionAction: {
    fontSize: 12,
    color: warmColors.accentDeep,
    fontWeight: "600",
    marginBottom: 14,
  },
  insightWrapper: { marginTop: 12 },
  affirmationCard: {
    marginTop: 20,
    backgroundColor: warmColors.surfaceDeep,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: warmColors.border,
    paddingHorizontal: 20,
    paddingVertical: 18,
    alignItems: "center",
  },
  affirmationText: {
    fontSize: 14,
    color: warmColors.accentDeep,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 22,
    letterSpacing: 0.1,
  },
  fabContainer: { position: "absolute", bottom: 0, left: 0, right: 0 },
});